sbatch ./jobs/Dirty_DBLP-ACM_baseline_run_1.slurm danilasm
sbatch ./jobs/Dirty_DBLP-ACM_baseline_run_2.slurm danilasm
sbatch ./jobs/Dirty_DBLP-ACM_baseline_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_gen_only_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_gen_only_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_gen_only_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_non_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_non_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_non_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_all_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_all_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_all_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_gen_only_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_gen_only_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_gen_only_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_matches_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_matches_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_matches_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_non_matches_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_non_matches_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_non_matches_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_all_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_all_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_all_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Dirty_DBLP-GoogleScholar_baseline_run_1.slurm danilasm
sbatch ./jobs/Dirty_DBLP-GoogleScholar_baseline_run_2.slurm danilasm
sbatch ./jobs/Dirty_DBLP-GoogleScholar_baseline_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_gen_only_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_gen_only_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_gen_only_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_non_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_non_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_non_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_all_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_all_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_all_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_gen_only_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_gen_only_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_gen_only_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_matches_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_matches_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_matches_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_non_matches_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_non_matches_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_non_matches_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_all_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_all_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_all_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Dirty_iTunes-Amazon_baseline_run_1.slurm danilasm
sbatch ./jobs/Dirty_iTunes-Amazon_baseline_run_2.slurm danilasm
sbatch ./jobs/Dirty_iTunes-Amazon_baseline_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_iTunes-Amazon_gen_only_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_iTunes-Amazon_gen_only_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_iTunes-Amazon_gen_only_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_gen_only_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_gen_only_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_gen_only_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_iTunes-Amazon_real_plus_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_iTunes-Amazon_real_plus_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_iTunes-Amazon_real_plus_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_iTunes-Amazon_real_plus_non_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_iTunes-Amazon_real_plus_non_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_iTunes-Amazon_real_plus_non_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_non_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_non_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_non_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_iTunes-Amazon_real_plus_all_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_iTunes-Amazon_real_plus_all_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_iTunes-Amazon_real_plus_all_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_all_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_all_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_all_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/Dirty_Walmart-Amazon_baseline_run_1.slurm danilasm
sbatch ./jobs/Dirty_Walmart-Amazon_baseline_run_2.slurm danilasm
sbatch ./jobs/Dirty_Walmart-Amazon_baseline_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_gen_only_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_gen_only_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_gen_only_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_non_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_non_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_non_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_all_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_all_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_all_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_gen_only_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_gen_only_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_gen_only_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_matches_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_matches_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_matches_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_non_matches_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_non_matches_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_non_matches_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_all_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_all_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_all_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Structured_Amazon-Google_baseline_run_1.slurm danilasm
sbatch ./jobs/Structured_Amazon-Google_baseline_run_2.slurm danilasm
sbatch ./jobs/Structured_Amazon-Google_baseline_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_gen_only_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_gen_only_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_gen_only_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_non_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_non_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_non_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_all_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_all_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_all_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_gen_only_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_gen_only_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_gen_only_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_matches_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_matches_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_matches_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_non_matches_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_non_matches_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_non_matches_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_all_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_all_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_all_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Structured_Beer_baseline_run_1.slurm danilasm
sbatch ./jobs/Structured_Beer_baseline_run_2.slurm danilasm
sbatch ./jobs/Structured_Beer_baseline_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Beer_gen_only_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Beer_gen_only_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Beer_gen_only_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_gen_only_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_gen_only_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_gen_only_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Beer_real_plus_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Beer_real_plus_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Beer_real_plus_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Beer_real_plus_non_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Beer_real_plus_non_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Beer_real_plus_non_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_non_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_non_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_non_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Beer_real_plus_all_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Beer_real_plus_all_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Beer_real_plus_all_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_all_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_all_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_all_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/Structured_DBLP-ACM_baseline_run_1.slurm danilasm
sbatch ./jobs/Structured_DBLP-ACM_baseline_run_2.slurm danilasm
sbatch ./jobs/Structured_DBLP-ACM_baseline_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_gen_only_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_gen_only_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_gen_only_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_non_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_non_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_non_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_all_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_all_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_all_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_gen_only_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_gen_only_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_gen_only_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_matches_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_matches_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_matches_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_non_matches_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_non_matches_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_non_matches_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_all_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_all_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_all_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Structured_DBLP-GoogleScholar_baseline_run_1.slurm danilasm
sbatch ./jobs/Structured_DBLP-GoogleScholar_baseline_run_2.slurm danilasm
sbatch ./jobs/Structured_DBLP-GoogleScholar_baseline_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_gen_only_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_gen_only_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_gen_only_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_non_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_non_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_non_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_all_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_all_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_all_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_gen_only_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_gen_only_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_gen_only_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_matches_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_matches_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_matches_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_non_matches_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_non_matches_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_non_matches_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_all_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_all_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_all_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Structured_Fodors-Zagats_baseline_run_1.slurm danilasm
sbatch ./jobs/Structured_Fodors-Zagats_baseline_run_2.slurm danilasm
sbatch ./jobs/Structured_Fodors-Zagats_baseline_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Fodors-Zagats_gen_only_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Fodors-Zagats_gen_only_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Fodors-Zagats_gen_only_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_gen_only_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_gen_only_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_gen_only_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Fodors-Zagats_real_plus_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Fodors-Zagats_real_plus_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Fodors-Zagats_real_plus_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Fodors-Zagats_real_plus_non_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Fodors-Zagats_real_plus_non_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Fodors-Zagats_real_plus_non_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_non_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_non_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_non_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Fodors-Zagats_real_plus_all_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Fodors-Zagats_real_plus_all_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Fodors-Zagats_real_plus_all_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_all_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_all_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_all_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/Structured_iTunes-Amazon_baseline_run_1.slurm danilasm
sbatch ./jobs/Structured_iTunes-Amazon_baseline_run_2.slurm danilasm
sbatch ./jobs/Structured_iTunes-Amazon_baseline_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_iTunes-Amazon_gen_only_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_iTunes-Amazon_gen_only_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_iTunes-Amazon_gen_only_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_gen_only_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_gen_only_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_gen_only_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_iTunes-Amazon_real_plus_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_iTunes-Amazon_real_plus_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_iTunes-Amazon_real_plus_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_iTunes-Amazon_real_plus_non_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_iTunes-Amazon_real_plus_non_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_iTunes-Amazon_real_plus_non_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_non_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_non_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_non_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_iTunes-Amazon_real_plus_all_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_iTunes-Amazon_real_plus_all_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_iTunes-Amazon_real_plus_all_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_all_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_all_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_all_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/Structured_Walmart-Amazon_baseline_run_1.slurm danilasm
sbatch ./jobs/Structured_Walmart-Amazon_baseline_run_2.slurm danilasm
sbatch ./jobs/Structured_Walmart-Amazon_baseline_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_gen_only_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_gen_only_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_gen_only_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_non_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_non_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_non_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_all_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_all_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_all_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_gen_only_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_gen_only_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_gen_only_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_matches_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_matches_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_matches_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_non_matches_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_non_matches_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_non_matches_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_all_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_all_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_all_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Textual_Abt-Buy_baseline_run_1.slurm danilasm
sbatch ./jobs/Textual_Abt-Buy_baseline_run_2.slurm danilasm
sbatch ./jobs/Textual_Abt-Buy_baseline_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_gen_only_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_gen_only_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_gen_only_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_non_matches_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_non_matches_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_non_matches_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_all_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_all_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_all_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_gen_only_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_gen_only_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_gen_only_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_matches_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_matches_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_matches_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_non_matches_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_non_matches_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_non_matches_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_all_decimated_run_1.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_all_decimated_run_2.slurm danilasm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_all_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_nft_decimated_run_3.slurm danilasm
