#!/bin/sh
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Beer_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_ft_decimated.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_ft_decimated.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_ft_decimated.slurm
