#!/bin/sh
sbatch ./jobs/Dirty_DBLP-ACM_baseline.slurm
sbatch ./jobs/Dirty_DBLP-ACM_baseline_decimated.slurm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_gen_only.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_nft.slurm
sbatch ./jobs/CTGAN_Dirty_DBLP-ACM_gen_only.slurm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_matches.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_nft.slurm
sbatch ./jobs/CTGAN_Dirty_DBLP-ACM_real_plus_matches.slurm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_non_matches.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_nft.slurm
sbatch ./jobs/CTGAN_Dirty_DBLP-ACM_real_plus_non_matches.slurm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_all.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_nft.slurm
sbatch ./jobs/CTGAN_Dirty_DBLP-ACM_real_plus_all.slurm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_gen_only_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_nft_decimated.slurm
sbatch ./jobs/CTGAN_Dirty_DBLP-ACM_gen_only_decimated.slurm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_matches_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_matches_nft_decimated.slurm
sbatch ./jobs/CTGAN_Dirty_DBLP-ACM_real_plus_matches_decimated.slurm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_non_matches_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_nft_decimated.slurm
sbatch ./jobs/CTGAN_Dirty_DBLP-ACM_real_plus_non_matches_decimated.slurm
sbatch ./jobs/Augmentation_Dirty_DBLP-ACM_real_plus_all_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_nft_decimated.slurm
sbatch ./jobs/CTGAN_Dirty_DBLP-ACM_real_plus_all_decimated.slurm
sbatch ./jobs/Dirty_DBLP-GoogleScholar_baseline.slurm
sbatch ./jobs/Dirty_DBLP-GoogleScholar_baseline_decimated.slurm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_gen_only.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_nft.slurm
sbatch ./jobs/CTGAN_Dirty_DBLP-GoogleScholar_gen_only.slurm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_matches.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_nft.slurm
sbatch ./jobs/CTGAN_Dirty_DBLP-GoogleScholar_real_plus_matches.slurm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_non_matches.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_nft.slurm
sbatch ./jobs/CTGAN_Dirty_DBLP-GoogleScholar_real_plus_non_matches.slurm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_all.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_nft.slurm
sbatch ./jobs/CTGAN_Dirty_DBLP-GoogleScholar_real_plus_all.slurm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_gen_only_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_nft_decimated.slurm
sbatch ./jobs/CTGAN_Dirty_DBLP-GoogleScholar_gen_only_decimated.slurm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_matches_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_matches_nft_decimated.slurm
sbatch ./jobs/CTGAN_Dirty_DBLP-GoogleScholar_real_plus_matches_decimated.slurm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_non_matches_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_nft_decimated.slurm
sbatch ./jobs/CTGAN_Dirty_DBLP-GoogleScholar_real_plus_non_matches_decimated.slurm
sbatch ./jobs/Augmentation_Dirty_DBLP-GoogleScholar_real_plus_all_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_nft_decimated.slurm
sbatch ./jobs/CTGAN_Dirty_DBLP-GoogleScholar_real_plus_all_decimated.slurm
sbatch ./jobs/Dirty_iTunes-Amazon_baseline.slurm
sbatch ./jobs/Dirty_iTunes-Amazon_baseline_decimated.slurm
sbatch ./jobs/Augmentation_Dirty_iTunes-Amazon_gen_only.slurm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_gen_only_nft.slurm
sbatch ./jobs/CTGAN_Dirty_iTunes-Amazon_gen_only.slurm
sbatch ./jobs/Augmentation_Dirty_iTunes-Amazon_real_plus_matches.slurm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_matches_nft.slurm
sbatch ./jobs/CTGAN_Dirty_iTunes-Amazon_real_plus_matches.slurm
sbatch ./jobs/Augmentation_Dirty_iTunes-Amazon_real_plus_non_matches.slurm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_non_matches_nft.slurm
sbatch ./jobs/CTGAN_Dirty_iTunes-Amazon_real_plus_non_matches.slurm
sbatch ./jobs/Augmentation_Dirty_iTunes-Amazon_real_plus_all.slurm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Dirty_iTunes-Amazon_real_plus_all_nft.slurm
sbatch ./jobs/CTGAN_Dirty_iTunes-Amazon_real_plus_all.slurm
sbatch ./jobs/Dirty_Walmart-Amazon_baseline.slurm
sbatch ./jobs/Dirty_Walmart-Amazon_baseline_decimated.slurm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_gen_only.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_nft.slurm
sbatch ./jobs/CTGAN_Dirty_Walmart-Amazon_gen_only.slurm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_matches.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_nft.slurm
sbatch ./jobs/CTGAN_Dirty_Walmart-Amazon_real_plus_matches.slurm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_non_matches.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_nft.slurm
sbatch ./jobs/CTGAN_Dirty_Walmart-Amazon_real_plus_non_matches.slurm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_all.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_nft.slurm
sbatch ./jobs/CTGAN_Dirty_Walmart-Amazon_real_plus_all.slurm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_gen_only_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_nft_decimated.slurm
sbatch ./jobs/CTGAN_Dirty_Walmart-Amazon_gen_only_decimated.slurm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_matches_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_matches_nft_decimated.slurm
sbatch ./jobs/CTGAN_Dirty_Walmart-Amazon_real_plus_matches_decimated.slurm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_non_matches_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_nft_decimated.slurm
sbatch ./jobs/CTGAN_Dirty_Walmart-Amazon_real_plus_non_matches_decimated.slurm
sbatch ./jobs/Augmentation_Dirty_Walmart-Amazon_real_plus_all_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_ft_decimated.slurm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_nft_decimated.slurm
sbatch ./jobs/CTGAN_Dirty_Walmart-Amazon_real_plus_all_decimated.slurm
sbatch ./jobs/Structured_Amazon-Google_baseline.slurm
sbatch ./jobs/Structured_Amazon-Google_baseline_decimated.slurm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_gen_only.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_nft.slurm
sbatch ./jobs/CTGAN_Structured_Amazon-Google_gen_only.slurm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_matches.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_nft.slurm
sbatch ./jobs/CTGAN_Structured_Amazon-Google_real_plus_matches.slurm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_non_matches.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_nft.slurm
sbatch ./jobs/CTGAN_Structured_Amazon-Google_real_plus_non_matches.slurm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_all.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_nft.slurm
sbatch ./jobs/CTGAN_Structured_Amazon-Google_real_plus_all.slurm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_gen_only_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_gen_only_nft_decimated.slurm
sbatch ./jobs/CTGAN_Structured_Amazon-Google_gen_only_decimated.slurm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_matches_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_matches_nft_decimated.slurm
sbatch ./jobs/CTGAN_Structured_Amazon-Google_real_plus_matches_decimated.slurm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_non_matches_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_non_matches_nft_decimated.slurm
sbatch ./jobs/CTGAN_Structured_Amazon-Google_real_plus_non_matches_decimated.slurm
sbatch ./jobs/Augmentation_Structured_Amazon-Google_real_plus_all_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Amazon-Google_real_plus_all_nft_decimated.slurm
sbatch ./jobs/CTGAN_Structured_Amazon-Google_real_plus_all_decimated.slurm
sbatch ./jobs/Structured_Beer_baseline.slurm
sbatch ./jobs/Structured_Beer_baseline_decimated.slurm
sbatch ./jobs/Augmentation_Structured_Beer_gen_only.slurm
sbatch ./jobs/GPT-2_Structured_Beer_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Structured_Beer_gen_only_nft.slurm
sbatch ./jobs/CTGAN_Structured_Beer_gen_only.slurm
sbatch ./jobs/Augmentation_Structured_Beer_real_plus_matches.slurm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_matches_nft.slurm
sbatch ./jobs/CTGAN_Structured_Beer_real_plus_matches.slurm
sbatch ./jobs/Augmentation_Structured_Beer_real_plus_non_matches.slurm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_non_matches_nft.slurm
sbatch ./jobs/CTGAN_Structured_Beer_real_plus_non_matches.slurm
sbatch ./jobs/Augmentation_Structured_Beer_real_plus_all.slurm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Structured_Beer_real_plus_all_nft.slurm
sbatch ./jobs/CTGAN_Structured_Beer_real_plus_all.slurm
sbatch ./jobs/Structured_DBLP-ACM_baseline.slurm
sbatch ./jobs/Structured_DBLP-ACM_baseline_decimated.slurm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_gen_only.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_nft.slurm
sbatch ./jobs/CTGAN_Structured_DBLP-ACM_gen_only.slurm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_matches.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_nft.slurm
sbatch ./jobs/CTGAN_Structured_DBLP-ACM_real_plus_matches.slurm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_non_matches.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_nft.slurm
sbatch ./jobs/CTGAN_Structured_DBLP-ACM_real_plus_non_matches.slurm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_all.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_nft.slurm
sbatch ./jobs/CTGAN_Structured_DBLP-ACM_real_plus_all.slurm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_gen_only_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_nft_decimated.slurm
sbatch ./jobs/CTGAN_Structured_DBLP-ACM_gen_only_decimated.slurm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_matches_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_matches_nft_decimated.slurm
sbatch ./jobs/CTGAN_Structured_DBLP-ACM_real_plus_matches_decimated.slurm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_non_matches_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_nft_decimated.slurm
sbatch ./jobs/CTGAN_Structured_DBLP-ACM_real_plus_non_matches_decimated.slurm
sbatch ./jobs/Augmentation_Structured_DBLP-ACM_real_plus_all_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_nft_decimated.slurm
sbatch ./jobs/CTGAN_Structured_DBLP-ACM_real_plus_all_decimated.slurm
sbatch ./jobs/Structured_DBLP-GoogleScholar_baseline.slurm
sbatch ./jobs/Structured_DBLP-GoogleScholar_baseline_decimated.slurm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_gen_only.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_nft.slurm
sbatch ./jobs/CTGAN_Structured_DBLP-GoogleScholar_gen_only.slurm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_matches.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_nft.slurm
sbatch ./jobs/CTGAN_Structured_DBLP-GoogleScholar_real_plus_matches.slurm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_non_matches.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_nft.slurm
sbatch ./jobs/CTGAN_Structured_DBLP-GoogleScholar_real_plus_non_matches.slurm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_all.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_nft.slurm
sbatch ./jobs/CTGAN_Structured_DBLP-GoogleScholar_real_plus_all.slurm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_gen_only_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_nft_decimated.slurm
sbatch ./jobs/CTGAN_Structured_DBLP-GoogleScholar_gen_only_decimated.slurm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_matches_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_matches_nft_decimated.slurm
sbatch ./jobs/CTGAN_Structured_DBLP-GoogleScholar_real_plus_matches_decimated.slurm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_non_matches_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_nft_decimated.slurm
sbatch ./jobs/CTGAN_Structured_DBLP-GoogleScholar_real_plus_non_matches_decimated.slurm
sbatch ./jobs/Augmentation_Structured_DBLP-GoogleScholar_real_plus_all_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_nft_decimated.slurm
sbatch ./jobs/CTGAN_Structured_DBLP-GoogleScholar_real_plus_all_decimated.slurm
sbatch ./jobs/Structured_Fodors-Zagats_baseline.slurm
sbatch ./jobs/Structured_Fodors-Zagats_baseline_decimated.slurm
sbatch ./jobs/Augmentation_Structured_Fodors-Zagats_gen_only.slurm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_gen_only_nft.slurm
sbatch ./jobs/CTGAN_Structured_Fodors-Zagats_gen_only.slurm
sbatch ./jobs/Augmentation_Structured_Fodors-Zagats_real_plus_matches.slurm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_matches_nft.slurm
sbatch ./jobs/CTGAN_Structured_Fodors-Zagats_real_plus_matches.slurm
sbatch ./jobs/Augmentation_Structured_Fodors-Zagats_real_plus_non_matches.slurm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_non_matches_nft.slurm
sbatch ./jobs/CTGAN_Structured_Fodors-Zagats_real_plus_non_matches.slurm
sbatch ./jobs/Augmentation_Structured_Fodors-Zagats_real_plus_all.slurm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Structured_Fodors-Zagats_real_plus_all_nft.slurm
sbatch ./jobs/CTGAN_Structured_Fodors-Zagats_real_plus_all.slurm
sbatch ./jobs/Structured_iTunes-Amazon_baseline.slurm
sbatch ./jobs/Structured_iTunes-Amazon_baseline_decimated.slurm
sbatch ./jobs/Augmentation_Structured_iTunes-Amazon_gen_only.slurm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_gen_only_nft.slurm
sbatch ./jobs/CTGAN_Structured_iTunes-Amazon_gen_only.slurm
sbatch ./jobs/Augmentation_Structured_iTunes-Amazon_real_plus_matches.slurm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_matches_nft.slurm
sbatch ./jobs/CTGAN_Structured_iTunes-Amazon_real_plus_matches.slurm
sbatch ./jobs/Augmentation_Structured_iTunes-Amazon_real_plus_non_matches.slurm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_non_matches_nft.slurm
sbatch ./jobs/CTGAN_Structured_iTunes-Amazon_real_plus_non_matches.slurm
sbatch ./jobs/Augmentation_Structured_iTunes-Amazon_real_plus_all.slurm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Structured_iTunes-Amazon_real_plus_all_nft.slurm
sbatch ./jobs/CTGAN_Structured_iTunes-Amazon_real_plus_all.slurm
sbatch ./jobs/Structured_Walmart-Amazon_baseline.slurm
sbatch ./jobs/Structured_Walmart-Amazon_baseline_decimated.slurm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_gen_only.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_nft.slurm
sbatch ./jobs/CTGAN_Structured_Walmart-Amazon_gen_only.slurm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_matches.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_nft.slurm
sbatch ./jobs/CTGAN_Structured_Walmart-Amazon_real_plus_matches.slurm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_non_matches.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_nft.slurm
sbatch ./jobs/CTGAN_Structured_Walmart-Amazon_real_plus_non_matches.slurm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_all.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_nft.slurm
sbatch ./jobs/CTGAN_Structured_Walmart-Amazon_real_plus_all.slurm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_gen_only_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_gen_only_nft_decimated.slurm
sbatch ./jobs/CTGAN_Structured_Walmart-Amazon_gen_only_decimated.slurm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_matches_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_matches_nft_decimated.slurm
sbatch ./jobs/CTGAN_Structured_Walmart-Amazon_real_plus_matches_decimated.slurm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_non_matches_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_non_matches_nft_decimated.slurm
sbatch ./jobs/CTGAN_Structured_Walmart-Amazon_real_plus_non_matches_decimated.slurm
sbatch ./jobs/Augmentation_Structured_Walmart-Amazon_real_plus_all_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_ft_decimated.slurm
sbatch ./jobs/GPT-2_Structured_Walmart-Amazon_real_plus_all_nft_decimated.slurm
sbatch ./jobs/CTGAN_Structured_Walmart-Amazon_real_plus_all_decimated.slurm
sbatch ./jobs/Textual_Abt-Buy_baseline.slurm
sbatch ./jobs/Textual_Abt-Buy_baseline_decimated.slurm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_gen_only.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_ft.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_nft.slurm
sbatch ./jobs/CTGAN_Textual_Abt-Buy_gen_only.slurm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_matches.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_ft.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_nft.slurm
sbatch ./jobs/CTGAN_Textual_Abt-Buy_real_plus_matches.slurm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_non_matches.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_ft.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_nft.slurm
sbatch ./jobs/CTGAN_Textual_Abt-Buy_real_plus_non_matches.slurm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_all.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_ft.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_nft.slurm
sbatch ./jobs/CTGAN_Textual_Abt-Buy_real_plus_all.slurm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_gen_only_decimated.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_ft_decimated.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_nft_decimated.slurm
sbatch ./jobs/CTGAN_Textual_Abt-Buy_gen_only_decimated.slurm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_matches_decimated.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_matches_nft_decimated.slurm
sbatch ./jobs/CTGAN_Textual_Abt-Buy_real_plus_matches_decimated.slurm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_non_matches_decimated.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_ft_decimated.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_nft_decimated.slurm
sbatch ./jobs/CTGAN_Textual_Abt-Buy_real_plus_non_matches_decimated.slurm
sbatch ./jobs/Augmentation_Textual_Abt-Buy_real_plus_all_decimated.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_ft_decimated.slurm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_nft_decimated.slurm
sbatch ./jobs/CTGAN_Textual_Abt-Buy_real_plus_all_decimated.slurm
