#!/bin/sh
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_Walmart-Amazon_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-GoogleScholar_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_nft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_nft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_nft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_gen_only_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_non_matches_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_nft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_nft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-GoogleScholar_real_plus_all_nft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_gen_only_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_non_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Dirty_DBLP-ACM_real_plus_all_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_gen_only_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_non_matches_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_ft_decimated_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_ft_decimated_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Structured_DBLP-ACM_real_plus_all_ft_decimated_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_gen_only_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_non_matches_ft_run_3.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_ft_run_1.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_ft_run_2.slurm danilasm
sbatch ./jobs/GPT-2_Textual_Abt-Buy_real_plus_all_ft_run_3.slurm danilasm