#!/bin/sh
sbatch ./jobs/Dirty_DBLP-ACM_baseline_run_1.slurm danilasm
sbatch ./jobs/Dirty_DBLP-ACM_baseline_run_2.slurm danilasm
sbatch ./jobs/Dirty_DBLP-ACM_baseline_run_3.slurm danilasm
sbatch ./jobs/Dirty_DBLP-GoogleScholar_baseline_run_1.slurm danilasm
sbatch ./jobs/Dirty_DBLP-GoogleScholar_baseline_run_2.slurm danilasm
sbatch ./jobs/Dirty_DBLP-GoogleScholar_baseline_run_3.slurm danilasm
sbatch ./jobs/Dirty_iTunes-Amazon_baseline_run_1.slurm danilasm
sbatch ./jobs/Dirty_iTunes-Amazon_baseline_run_2.slurm danilasm
sbatch ./jobs/Dirty_iTunes-Amazon_baseline_run_3.slurm danilasm
sbatch ./jobs/Dirty_Walmart-Amazon_baseline_run_1.slurm danilasm
sbatch ./jobs/Dirty_Walmart-Amazon_baseline_run_2.slurm danilasm
sbatch ./jobs/Dirty_Walmart-Amazon_baseline_run_3.slurm danilasm
sbatch ./jobs/Structured_Amazon-Google_baseline_run_1.slurm danilasm
sbatch ./jobs/Structured_Amazon-Google_baseline_run_2.slurm danilasm
sbatch ./jobs/Structured_Amazon-Google_baseline_run_3.slurm danilasm
sbatch ./jobs/Structured_Beer_baseline_run_1.slurm danilasm
sbatch ./jobs/Structured_Beer_baseline_run_2.slurm danilasm
sbatch ./jobs/Structured_Beer_baseline_run_3.slurm danilasm
sbatch ./jobs/Structured_DBLP-ACM_baseline_run_1.slurm danilasm
sbatch ./jobs/Structured_DBLP-ACM_baseline_run_2.slurm danilasm
sbatch ./jobs/Structured_DBLP-ACM_baseline_run_3.slurm danilasm
sbatch ./jobs/Structured_DBLP-GoogleScholar_baseline_run_1.slurm danilasm
sbatch ./jobs/Structured_DBLP-GoogleScholar_baseline_run_2.slurm danilasm
sbatch ./jobs/Structured_DBLP-GoogleScholar_baseline_run_3.slurm danilasm
sbatch ./jobs/Structured_Fodors-Zagats_baseline_run_1.slurm danilasm
sbatch ./jobs/Structured_Fodors-Zagats_baseline_run_2.slurm danilasm
sbatch ./jobs/Structured_Fodors-Zagats_baseline_run_3.slurm danilasm
sbatch ./jobs/Structured_iTunes-Amazon_baseline_run_1.slurm danilasm
sbatch ./jobs/Structured_iTunes-Amazon_baseline_run_2.slurm danilasm
sbatch ./jobs/Structured_iTunes-Amazon_baseline_run_3.slurm danilasm
sbatch ./jobs/Structured_Walmart-Amazon_baseline_run_1.slurm danilasm
sbatch ./jobs/Structured_Walmart-Amazon_baseline_run_2.slurm danilasm
sbatch ./jobs/Structured_Walmart-Amazon_baseline_run_3.slurm danilasm
sbatch ./jobs/Textual_Abt-Buy_baseline_run_1.slurm danilasm
sbatch ./jobs/Textual_Abt-Buy_baseline_run_2.slurm danilasm
sbatch ./jobs/Textual_Abt-Buy_baseline_run_3.slurm danilasm
