#!/bin/sh
sbatch ./jobs/Dirty_DBLP-ACM_baseline.slurm
sbatch ./jobs/Dirty_DBLP-ACM_baseline_decimated.slurm
sbatch ./jobs/Dirty_DBLP-GoogleScholar_baseline.slurm
sbatch ./jobs/Dirty_DBLP-GoogleScholar_baseline_decimated.slurm
sbatch ./jobs/Dirty_iTunes-Amazon_baseline.slurm
sbatch ./jobs/Dirty_iTunes-Amazon_baseline_decimated.slurm
sbatch ./jobs/Dirty_Walmart-Amazon_baseline.slurm
sbatch ./jobs/Dirty_Walmart-Amazon_baseline_decimated.slurm
sbatch ./jobs/Structured_Amazon-Google_baseline.slurm
sbatch ./jobs/Structured_Amazon-Google_baseline_decimated.slurm
sbatch ./jobs/Structured_Beer_baseline.slurm
sbatch ./jobs/Structured_Beer_baseline_decimated.slurm
sbatch ./jobs/Structured_DBLP-ACM_baseline.slurm
sbatch ./jobs/Structured_DBLP-ACM_baseline_decimated.slurm
sbatch ./jobs/Structured_DBLP-GoogleScholar_baseline.slurm
sbatch ./jobs/Structured_DBLP-GoogleScholar_baseline_decimated.slurm
sbatch ./jobs/Structured_Fodors-Zagats_baseline.slurm
sbatch ./jobs/Structured_Fodors-Zagats_baseline_decimated.slurm
sbatch ./jobs/Structured_iTunes-Amazon_baseline.slurm
sbatch ./jobs/Structured_iTunes-Amazon_baseline_decimated.slurm
sbatch ./jobs/Structured_Walmart-Amazon_baseline.slurm
sbatch ./jobs/Structured_Walmart-Amazon_baseline_decimated.slurm
sbatch ./jobs/Textual_Abt-Buy_baseline.slurm
sbatch ./jobs/Textual_Abt-Buy_baseline_decimated.slurm
