#!/bin/sh
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-ACMBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-GoogleScholarBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_iTunes-AmazonBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_Walmart-AmazonBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Amazon-GoogleBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_BeerBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-ACMBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-GoogleScholarBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Fodors-ZagatsBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_iTunes-AmazonBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Walmart-AmazonBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Textual_Abt-BuyBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-ACMmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-GoogleScholarmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_iTunes-Amazonmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_Walmart-Amazonmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Amazon-Googlematches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Beermatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-ACMmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-GoogleScholarmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Fodors-Zagatsmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_iTunes-Amazonmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Walmart-Amazonmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Textual_Abt-Buymatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-ACMreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-GoogleScholarreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_iTunes-Amazonreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_Walmart-Amazonreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Amazon-Googlereal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Beerreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-ACMreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-GoogleScholarreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Fodors-Zagatsreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_iTunes-Amazonreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Walmart-Amazonreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Textual_Abt-Buyreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-ACMreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-GoogleScholarreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_iTunes-Amazonreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_Walmart-Amazonreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Amazon-Googlereal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Beerreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-ACMreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-GoogleScholarreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Fodors-Zagatsreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_iTunes-Amazonreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Walmart-Amazonreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Textual_Abt-Buyreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-ACMreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-GoogleScholarreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_iTunes-Amazonreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_Walmart-Amazonreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Amazon-Googlereal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Beerreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-ACMreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-GoogleScholarreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Fodors-Zagatsreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_iTunes-Amazonreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Walmart-Amazonreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Textual_Abt-Buyreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-ACMdecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-GoogleScholardecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_iTunes-Amazondecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_Walmart-Amazondecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Amazon-Googledecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Beerdecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-ACMdecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-GoogleScholardecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Fodors-Zagatsdecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_iTunes-Amazondecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Walmart-Amazondecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Textual_Abt-Buydecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-ACMdecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-GoogleScholardecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_iTunes-Amazondecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_Walmart-Amazondecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Amazon-Googledecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Beerdecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-ACMdecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-GoogleScholardecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Fodors-Zagatsdecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_iTunes-Amazondecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Walmart-Amazondecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Textual_Abt-Buydecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-ACMdecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-GoogleScholardecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_iTunes-Amazondecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_Walmart-Amazondecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Amazon-Googledecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Beerdecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-ACMdecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-GoogleScholardecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Fodors-Zagatsdecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_iTunes-Amazondecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Walmart-Amazondecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Textual_Abt-Buydecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-ACMdecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-GoogleScholardecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_iTunes-Amazondecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_Walmart-Amazondecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Amazon-Googledecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Beerdecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-ACMdecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-GoogleScholardecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Fodors-Zagatsdecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_iTunes-Amazondecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Walmart-Amazondecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Textual_Abt-Buydecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-ACMdecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_DBLP-GoogleScholardecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_iTunes-Amazondecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Dirty_Walmart-Amazondecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Amazon-Googledecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Beerdecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-ACMdecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_DBLP-GoogleScholardecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Fodors-Zagatsdecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_iTunes-Amazondecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Structured_Walmart-Amazondecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/CTGAN/Textual_Abt-Buydecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-ACMBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-GoogleScholarBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_iTunes-AmazonBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_Walmart-AmazonBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Amazon-GoogleBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_BeerBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-ACMBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-GoogleScholarBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Fodors-ZagatsBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_iTunes-AmazonBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Walmart-AmazonBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Textual_Abt-BuyBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-ACMmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-GoogleScholarmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_iTunes-Amazonmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_Walmart-Amazonmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Amazon-Googlematches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Beermatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-ACMmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-GoogleScholarmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Fodors-Zagatsmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_iTunes-Amazonmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Walmart-Amazonmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Textual_Abt-Buymatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-ACMreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-GoogleScholarreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_iTunes-Amazonreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_Walmart-Amazonreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Amazon-Googlereal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Beerreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-ACMreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-GoogleScholarreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Fodors-Zagatsreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_iTunes-Amazonreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Walmart-Amazonreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Textual_Abt-Buyreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-ACMreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-GoogleScholarreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_iTunes-Amazonreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_Walmart-Amazonreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Amazon-Googlereal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Beerreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-ACMreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-GoogleScholarreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Fodors-Zagatsreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_iTunes-Amazonreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Walmart-Amazonreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Textual_Abt-Buyreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-ACMreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-GoogleScholarreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_iTunes-Amazonreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_Walmart-Amazonreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Amazon-Googlereal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Beerreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-ACMreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-GoogleScholarreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Fodors-Zagatsreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_iTunes-Amazonreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Walmart-Amazonreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Textual_Abt-Buyreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-ACMdecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-GoogleScholardecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_iTunes-Amazondecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_Walmart-Amazondecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Amazon-Googledecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Beerdecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-ACMdecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-GoogleScholardecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Fodors-Zagatsdecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_iTunes-Amazondecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Walmart-Amazondecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Textual_Abt-Buydecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-ACMdecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-GoogleScholardecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_iTunes-Amazondecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_Walmart-Amazondecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Amazon-Googledecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Beerdecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-ACMdecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-GoogleScholardecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Fodors-Zagatsdecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_iTunes-Amazondecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Walmart-Amazondecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Textual_Abt-Buydecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-ACMdecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-GoogleScholardecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_iTunes-Amazondecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_Walmart-Amazondecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Amazon-Googledecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Beerdecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-ACMdecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-GoogleScholardecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Fodors-Zagatsdecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_iTunes-Amazondecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Walmart-Amazondecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Textual_Abt-Buydecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-ACMdecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-GoogleScholardecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_iTunes-Amazondecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_Walmart-Amazondecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Amazon-Googledecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Beerdecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-ACMdecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-GoogleScholardecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Fodors-Zagatsdecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_iTunes-Amazondecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Walmart-Amazondecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Textual_Abt-Buydecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-ACMdecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_DBLP-GoogleScholardecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_iTunes-Amazondecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Dirty_Walmart-Amazondecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Amazon-Googledecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Beerdecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-ACMdecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_DBLP-GoogleScholardecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Fodors-Zagatsdecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_iTunes-Amazondecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Structured_Walmart-Amazondecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_ft/Textual_Abt-Buydecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-ACMBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-GoogleScholarBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_iTunes-AmazonBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_Walmart-AmazonBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Amazon-GoogleBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_BeerBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-ACMBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-GoogleScholarBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Fodors-ZagatsBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_iTunes-AmazonBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Walmart-AmazonBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Textual_Abt-BuyBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-ACMmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-GoogleScholarmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_iTunes-Amazonmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_Walmart-Amazonmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Amazon-Googlematches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Beermatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-ACMmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-GoogleScholarmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Fodors-Zagatsmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_iTunes-Amazonmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Walmart-Amazonmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Textual_Abt-Buymatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-ACMreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-GoogleScholarreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_iTunes-Amazonreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_Walmart-Amazonreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Amazon-Googlereal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Beerreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-ACMreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-GoogleScholarreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Fodors-Zagatsreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_iTunes-Amazonreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Walmart-Amazonreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Textual_Abt-Buyreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-ACMreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-GoogleScholarreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_iTunes-Amazonreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_Walmart-Amazonreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Amazon-Googlereal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Beerreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-ACMreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-GoogleScholarreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Fodors-Zagatsreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_iTunes-Amazonreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Walmart-Amazonreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Textual_Abt-Buyreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-ACMreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-GoogleScholarreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_iTunes-Amazonreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_Walmart-Amazonreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Amazon-Googlereal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Beerreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-ACMreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-GoogleScholarreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Fodors-Zagatsreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_iTunes-Amazonreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Walmart-Amazonreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Textual_Abt-Buyreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-ACMdecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-GoogleScholardecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_iTunes-Amazondecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_Walmart-Amazondecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Amazon-Googledecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Beerdecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-ACMdecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-GoogleScholardecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Fodors-Zagatsdecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_iTunes-Amazondecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Walmart-Amazondecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Textual_Abt-Buydecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-ACMdecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-GoogleScholardecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_iTunes-Amazondecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_Walmart-Amazondecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Amazon-Googledecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Beerdecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-ACMdecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-GoogleScholardecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Fodors-Zagatsdecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_iTunes-Amazondecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Walmart-Amazondecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Textual_Abt-Buydecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-ACMdecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-GoogleScholardecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_iTunes-Amazondecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_Walmart-Amazondecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Amazon-Googledecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Beerdecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-ACMdecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-GoogleScholardecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Fodors-Zagatsdecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_iTunes-Amazondecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Walmart-Amazondecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Textual_Abt-Buydecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-ACMdecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-GoogleScholardecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_iTunes-Amazondecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_Walmart-Amazondecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Amazon-Googledecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Beerdecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-ACMdecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-GoogleScholardecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Fodors-Zagatsdecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_iTunes-Amazondecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Walmart-Amazondecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Textual_Abt-Buydecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-ACMdecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_DBLP-GoogleScholardecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_iTunes-Amazondecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Dirty_Walmart-Amazondecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Amazon-Googledecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Beerdecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-ACMdecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_DBLP-GoogleScholardecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Fodors-Zagatsdecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_iTunes-Amazondecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Structured_Walmart-Amazondecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/GPT-2_nft/Textual_Abt-Buydecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-ACMBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-GoogleScholarBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_iTunes-AmazonBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_Walmart-AmazonBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Amazon-GoogleBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_BeerBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-ACMBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-GoogleScholarBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Fodors-ZagatsBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_iTunes-AmazonBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Walmart-AmazonBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Textual_Abt-BuyBaseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-ACMmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-GoogleScholarmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_iTunes-Amazonmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_Walmart-Amazonmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Amazon-Googlematches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Beermatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-ACMmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-GoogleScholarmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Fodors-Zagatsmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_iTunes-Amazonmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Walmart-Amazonmatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Textual_Abt-Buymatches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-ACMreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-GoogleScholarreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_iTunes-Amazonreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_Walmart-Amazonreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Amazon-Googlereal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Beerreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-ACMreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-GoogleScholarreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Fodors-Zagatsreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_iTunes-Amazonreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Walmart-Amazonreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Textual_Abt-Buyreal_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-ACMreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-GoogleScholarreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_iTunes-Amazonreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_Walmart-Amazonreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Amazon-Googlereal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Beerreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-ACMreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-GoogleScholarreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Fodors-Zagatsreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_iTunes-Amazonreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Walmart-Amazonreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Textual_Abt-Buyreal_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-ACMreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-GoogleScholarreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_iTunes-Amazonreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_Walmart-Amazonreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Amazon-Googlereal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Beerreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-ACMreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-GoogleScholarreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Fodors-Zagatsreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_iTunes-Amazonreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Walmart-Amazonreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Textual_Abt-Buyreal_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-ACMdecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-GoogleScholardecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_iTunes-Amazondecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_Walmart-Amazondecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Amazon-Googledecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Beerdecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-ACMdecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-GoogleScholardecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Fodors-Zagatsdecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_iTunes-Amazondecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Walmart-Amazondecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Textual_Abt-Buydecimate_Baseline.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-ACMdecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-GoogleScholardecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_iTunes-Amazondecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_Walmart-Amazondecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Amazon-Googledecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Beerdecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-ACMdecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-GoogleScholardecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Fodors-Zagatsdecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_iTunes-Amazondecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Walmart-Amazondecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Textual_Abt-Buydecimate_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-ACMdecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-GoogleScholardecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_iTunes-Amazondecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_Walmart-Amazondecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Amazon-Googledecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Beerdecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-ACMdecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-GoogleScholardecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Fodors-Zagatsdecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_iTunes-Amazondecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Walmart-Amazondecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Textual_Abt-Buydecimate_real_data_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-ACMdecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-GoogleScholardecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_iTunes-Amazondecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_Walmart-Amazondecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Amazon-Googledecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Beerdecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-ACMdecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-GoogleScholardecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Fodors-Zagatsdecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_iTunes-Amazondecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Walmart-Amazondecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Textual_Abt-Buydecimate_real_data_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-ACMdecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_DBLP-GoogleScholardecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_iTunes-Amazondecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Dirty_Walmart-Amazondecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Amazon-Googledecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Beerdecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-ACMdecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_DBLP-GoogleScholardecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Fodors-Zagatsdecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_iTunes-Amazondecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Structured_Walmart-Amazondecimate_real_data_matches_non-matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/match_jobs/Augmentation/Textual_Abt-Buydecimate_real_data_matches_non-matches.slurm alekssim
