#!/bin/sh
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Dirty_DBLP-ACM_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Dirty_DBLP-ACM_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Dirty_DBLP-ACM_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Dirty_DBLP-ACM_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Dirty_DBLP-GoogleScholar_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Dirty_DBLP-GoogleScholar_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Dirty_DBLP-GoogleScholar_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Dirty_DBLP-GoogleScholar_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Dirty_iTunes-Amazon_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Dirty_iTunes-Amazon_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Dirty_iTunes-Amazon_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Dirty_iTunes-Amazon_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Dirty_Walmart-Amazon_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Dirty_Walmart-Amazon_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Dirty_Walmart-Amazon_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Dirty_Walmart-Amazon_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_Amazon-Google_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_Amazon-Google_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_Amazon-Google_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_Amazon-Google_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_Beer_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_Beer_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_Beer_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_Beer_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_DBLP-ACM_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_DBLP-ACM_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_DBLP-ACM_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_DBLP-ACM_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_DBLP-GoogleScholar_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_DBLP-GoogleScholar_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_DBLP-GoogleScholar_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_DBLP-GoogleScholar_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_Fodors-Zagats_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_Fodors-Zagats_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_Fodors-Zagats_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_Fodors-Zagats_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_iTunes-Amazon_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_iTunes-Amazon_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_iTunes-Amazon_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_iTunes-Amazon_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_Walmart-Amazon_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_Walmart-Amazon_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_Walmart-Amazon_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Structured_Walmart-Amazon_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Textual_Abt-Buy_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Textual_Abt-Buy_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Textual_Abt-Buy_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_ft/Textual_Abt-Buy_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Dirty_DBLP-ACM_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Dirty_DBLP-ACM_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Dirty_DBLP-ACM_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Dirty_DBLP-ACM_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Dirty_DBLP-GoogleScholar_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Dirty_DBLP-GoogleScholar_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Dirty_DBLP-GoogleScholar_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Dirty_DBLP-GoogleScholar_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Dirty_iTunes-Amazon_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Dirty_iTunes-Amazon_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Dirty_iTunes-Amazon_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Dirty_iTunes-Amazon_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Dirty_Walmart-Amazon_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Dirty_Walmart-Amazon_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Dirty_Walmart-Amazon_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Dirty_Walmart-Amazon_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_Amazon-Google_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_Amazon-Google_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_Amazon-Google_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_Amazon-Google_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_Beer_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_Beer_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_Beer_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_Beer_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_DBLP-ACM_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_DBLP-ACM_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_DBLP-ACM_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_DBLP-ACM_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_DBLP-GoogleScholar_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_DBLP-GoogleScholar_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_DBLP-GoogleScholar_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_DBLP-GoogleScholar_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_Fodors-Zagats_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_Fodors-Zagats_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_Fodors-Zagats_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_Fodors-Zagats_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_iTunes-Amazon_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_iTunes-Amazon_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_iTunes-Amazon_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_iTunes-Amazon_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_Walmart-Amazon_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_Walmart-Amazon_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_Walmart-Amazon_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Structured_Walmart-Amazon_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Textual_Abt-Buy_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Textual_Abt-Buy_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Textual_Abt-Buy_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/GPT-2_nft/Textual_Abt-Buy_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Dirty_DBLP-ACM_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Dirty_DBLP-ACM_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Dirty_DBLP-ACM_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Dirty_DBLP-ACM_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Dirty_DBLP-GoogleScholar_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Dirty_DBLP-GoogleScholar_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Dirty_DBLP-GoogleScholar_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Dirty_DBLP-GoogleScholar_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Dirty_iTunes-Amazon_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Dirty_iTunes-Amazon_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Dirty_iTunes-Amazon_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Dirty_iTunes-Amazon_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Dirty_Walmart-Amazon_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Dirty_Walmart-Amazon_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Dirty_Walmart-Amazon_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Dirty_Walmart-Amazon_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_Amazon-Google_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_Amazon-Google_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_Amazon-Google_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_Amazon-Google_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_Beer_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_Beer_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_Beer_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_Beer_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_DBLP-ACM_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_DBLP-ACM_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_DBLP-ACM_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_DBLP-ACM_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_DBLP-GoogleScholar_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_DBLP-GoogleScholar_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_DBLP-GoogleScholar_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_DBLP-GoogleScholar_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_Fodors-Zagats_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_Fodors-Zagats_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_Fodors-Zagats_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_Fodors-Zagats_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_iTunes-Amazon_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_iTunes-Amazon_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_iTunes-Amazon_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_iTunes-Amazon_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_Walmart-Amazon_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_Walmart-Amazon_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_Walmart-Amazon_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Structured_Walmart-Amazon_non_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Textual_Abt-Buy_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Textual_Abt-Buy_non_matches.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Textual_Abt-Buy_matches_decimated.slurm alekssim
sbatch /cluster/home/alekssim/Documents/IDUN/Idun/CTGAN/parse_jobs/Augmentation/Textual_Abt-Buy_non_matches_decimated.slurm alekssim
